name: o2
dependencies:
  - python=3.8
  - bokeh
  - ipython
  - jupyter
  - paramiko
  - pip
  - requests
  - scp
  - pip:
      - google-cloud-compute
      - jupyter-book
      - git+https://github.com/alecgunny/cloud-utils@main
      - git+https://github.com/alecgunny/typeo@main