name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    # Install dependencies
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: o2
        environment-file: environment.yml

    - name: Build book
      shell: bash -l {0}
      run: |
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html